/* Arken Fox */
user_pref("_user.js.parrot","START:Ohyes,theNorwegianBlue...what'swrongwithit?");
user_pref("_user.js.parrot","0200syntaxerror:theparrot'sdefinitelydeceased!");
user_pref("_user.js.parrot","0300syntaxerror:theparrot'snotpinin'forthefjords!");
user_pref("_user.js.parrot","0100syntaxerror:theparrot'sdead!");
user_pref("_user.js.parrot","0600syntaxerror:theparrot'snomore!");
user_pref("_user.js.parrot","0400syntaxerror:theparrot'spassedon!");
user_pref("_user.js.parrot","0800syntaxerror:theparrot'sceasedtobe!");
user_pref("_user.js.parrot","0900syntaxerror:theparrot'sexpired!");
user_pref("_user.js.parrot","1000syntaxerror:theparrot'sgonetomeet'ismaker!");
user_pref("_user.js.parrot","1200syntaxerror:theparrot'sastiff!");
user_pref("_user.js.parrot","9999syntaxerror:theparrot'sshuffledoff'ismortalcoil!");
user_pref("_user.js.parrot","SUCCESS:Nonohe'snotdead,he's,he'srestin'!");
user_pref("_user.js.parrot","0700syntaxerror:theparrot'sgivenuptheghost!");
user_pref("_user.js.parrot","7000syntaxerror:theparrot'spushingupdaisies!");
user_pref("_user.js.parrot","8000syntaxerror:theparrot'scrossedtheJordan");
user_pref("_user.js.parrot","8500syntaxerror:theparrot'soffthetwig!");
user_pref("_user.js.parrot","9000syntaxerror:theparrot'scashedin'ischips!");
user_pref("_user.js.parrot","1700syntaxerror:theparrot'sbitthedust!");
user_pref("_user.js.parrot","1600syntaxerror:theparrotrestsinpeace!");
user_pref("_user.js.parrot","2000syntaxerror:theparrot'ssnuffedit!");
user_pref("_user.js.parrot","2600syntaxerror:theparrot'srundownthecurtain!");
user_pref("_user.js.parrot","2400syntaxerror:theparrot'skickedthebucket!");
user_pref("_user.js.parrot","2800syntaxerror:theparrot'sbleedin'demised!");
user_pref("_user.js.parrot","2700syntaxerror:theparrot'sjoinedthebleedin'choirinvisible!");
user_pref("_user.js.parrot","4000syntaxerror:theparrot'sbereftoflife!");
user_pref("_user.js.parrot","4500syntaxerror:theparrot'spopped'isclogs");
user_pref("_user.js.parrot","5000syntaxerror:theparrot'staken'islastbow");
user_pref("_user.js.parrot","5500syntaxerror:thisisanex-parrot!");
user_pref("_user.js.parrot","6000syntaxerror:theparrot's'istory!");

user_pref("browser.aboutConfig.showWarning",false);
user_pref("browser.startup.page",0);
user_pref("browser.startup.homepage","about:newtab");
user_pref("browser.newtabpage.enabled",false);
user_pref("browser.newtabpage.activity-stream.showSponsored",false);
user_pref("browser.newtabpage.activity-stream.showSponsoredTopSites",false);
user_pref("browser.newtabpage.activity-stream.default.sites","");
user_pref("geo.provider.ms-windows-location",false);
user_pref("geo.provider.use_corelocation",false);
user_pref("geo.provider.use_geoclue",false);
user_pref("extensions.getAddons.showPane",false);
user_pref("extensions.htmlaboutaddons.recommendations.enabled",false);
user_pref("browser.discovery.enabled",false);
user_pref("browser.shopping.experience2023.enabled",false);
user_pref("browser.newtabpage.activity-stream.feeds.telemetry",false);
user_pref("browser.newtabpage.activity-stream.telemetry",false);
user_pref("app.shield.optoutstudies.enabled",false);
user_pref("app.normandy.enabled",false);
user_pref("app.normandy.api_url","");
user_pref("breakpad.reportURL","");
user_pref("browser.tabs.crashReporting.sendReport",false);
user_pref("browser.crashReports.unsubmittedCheck.autoSubmit2",false);
user_pref("captivedetect.canonicalURL","");
user_pref("network.captive-portal-service.enabled",false);
user_pref("network.connectivity-service.enabled",false);
user_pref("browser.safebrowsing.downloads.remote.enabled",false);
user_pref("network.prefetch-next",false);
user_pref("network.dns.disablePrefetch",true);
user_pref("network.dns.disablePrefetchFromHTTPS",true);
user_pref("network.predictor.enabled",false);
user_pref("network.predictor.enable-prefetch",false);
user_pref("network.http.speculative-parallel-limit",0);
user_pref("browser.places.speculativeConnect.enabled",false);
user_pref("network.proxy.socks_remote_dns",true);
user_pref("network.file.disable_unc_paths",true);
user_pref("network.gio.supported-protocols","");
user_pref("browser.urlbar.speculativeConnect.enabled",false);
user_pref("browser.urlbar.quicksuggest.enabled",false);
user_pref("browser.urlbar.suggest.quicksuggest.nonsponsored",false);
user_pref("browser.urlbar.suggest.quicksuggest.sponsored",false);
user_pref("browser.search.suggest.enabled",false);
user_pref("browser.urlbar.suggest.searches",false);
user_pref("browser.urlbar.trending.featureGate",false);
user_pref("browser.urlbar.addons.featureGate",false);
user_pref("browser.urlbar.fakespot.featureGate",false);
user_pref("browser.urlbar.mdn.featureGate",false);
user_pref("browser.urlbar.pocket.featureGate",false);
user_pref("browser.urlbar.weather.featureGate",false);
user_pref("browser.urlbar.yelp.featureGate",false);
user_pref("browser.formfill.enable",false);
user_pref("browser.search.separatePrivateDefault",true);
user_pref("browser.search.separatePrivateDefault.ui.enabled",true);
user_pref("signon.autofillForms",false);
user_pref("signon.formlessCapture.enabled",false);
user_pref("network.auth.subresource-http-auth-allow",1);
user_pref("browser.cache.disk.enable",false);
user_pref("browser.privatebrowsing.forceMediaMemoryCache",true);
user_pref("media.memory_cache_max_size",65536);
user_pref("browser.sessionstore.privacy_level",2);
user_pref("toolkit.winRegisterApplicationRestart",false);
user_pref("browser.shell.shortcutFavicons",false);
user_pref("security.ssl.require_safe_negotiation",true);
user_pref("security.tls.enable_0rtt_data",false);
user_pref("security.OCSP.enabled",1);
user_pref("security.OCSP.require",true);
user_pref("security.cert_pinning.enforcement_level",2);
user_pref("security.remote_settings.crlite_filters.enabled",true);
user_pref("security.pki.crlite_mode",2);
user_pref("dom.security.https_only_mode",true);
user_pref("dom.security.https_only_mode_send_http_background_request",false);
user_pref("security.ssl.treat_unsafe_negotiation_as_broken",true);
user_pref("browser.xul.error_pages.expert_bad_cert",true);
user_pref("network.http.referer.XOriginTrimmingPolicy",2);
user_pref("privacy.userContext.enabled",true);
user_pref("privacy.userContext.ui.enabled",true);
user_pref("media.peerconnection.ice.proxy_only_if_behind_proxy",true);
user_pref("media.peerconnection.ice.default_address_only",true);
user_pref("dom.disable_window_move_resize",true);
user_pref("browser.download.start_downloads_in_tmp_dir",true);
user_pref("browser.helperApps.deleteTempFileOnExit",true);
user_pref("browser.uitour.enabled",false);
user_pref("devtools.debugger.remote-enabled",false);
user_pref("permissions.manager.defaultsUrl","");
user_pref("network.IDN_show_punycode",true);
user_pref("pdfjs.disabled",false);
user_pref("pdfjs.enableScripting",false);
user_pref("browser.tabs.searchclipboardfor.middleclick",false);
user_pref("browser.contentanalysis.enabled",false);
user_pref("browser.contentanalysis.default_result",0);
user_pref("browser.download.useDownloadDir",false);
user_pref("browser.download.alwaysOpenPanel",false);
user_pref("browser.download.manager.addToRecentDocs",false);
user_pref("browser.download.always_ask_before_handling_new_types",true);
user_pref("extensions.enabledScopes",5);
user_pref("extensions.postDownloadThirdPartyPrompt",false);
user_pref("browser.contentblocking.category","strict");
user_pref("privacy.sanitize.sanitizeOnShutdown",true);
user_pref("privacy.clearOnShutdown_v2.cache",true);
user_pref("privacy.clearOnShutdown_v2.historyFormDataAndDownloads",true);
user_pref("privacy.clearOnShutdown_v2.browsingHistoryAndDownloads",true);
user_pref("privacy.clearOnShutdown_v2.downloads",true);
user_pref("privacy.clearOnShutdown_v2.formdata",true);
user_pref("privacy.clearOnShutdown_v2.cookiesAndStorage",true);
user_pref("privacy.clearSiteData.cache",true);
user_pref("privacy.clearSiteData.cookiesAndStorage",false);
user_pref("privacy.clearSiteData.historyFormDataAndDownloads",true);
user_pref("privacy.clearSiteData.browsingHistoryAndDownloads",true);
user_pref("privacy.clearSiteData.formdata",true);
user_pref("privacy.clearHistory.cache",true);
user_pref("privacy.clearHistory.cookiesAndStorage",false);
user_pref("privacy.clearHistory.historyFormDataAndDownloads",true);
user_pref("privacy.clearHistory.browsingHistoryAndDownloads",true);
user_pref("privacy.clearHistory.formdata",true);
user_pref("privacy.sanitize.timeSpan",0);
user_pref("privacy.window.maxInnerWidth",1600);
user_pref("privacy.window.maxInnerHeight",900);
user_pref("privacy.resistFingerprinting.block_mozAddonManager",true);
user_pref("privacy.spoof_english",1);
user_pref("browser.display.use_system_colors",false);
user_pref("widget.non-native-theme.use-theme-accent",false);
user_pref("browser.link.open_newwindow",3);
user_pref("browser.link.open_newwindow.restriction",0);
user_pref("extensions.blocklist.enabled",true);
user_pref("network.http.referer.spoofSource",false);
user_pref("security.dialog_enable_delay",1000);
user_pref("privacy.firstparty.isolate",false);
user_pref("extensions.webcompat.enable_shims",true);
user_pref("security.tls.version.enable-deprecated",false);
user_pref("extensions.webcompat-reporter.enabled",false);
user_pref("extensions.quarantinedDomains.enabled",true);
user_pref("datareporting.policy.dataSubmissionEnabled",false);
user_pref("datareporting.healthreport.uploadEnabled",false);
user_pref("toolkit.telemetry.unified",false);
user_pref("toolkit.telemetry.enabled",false);
user_pref("toolkit.telemetry.server","data:,");
user_pref("toolkit.telemetry.archive.enabled",false);
user_pref("toolkit.telemetry.newProfilePing.enabled",false);
user_pref("toolkit.telemetry.shutdownPingSender.enabled",false);
user_pref("toolkit.telemetry.updatePing.enabled",false);
user_pref("toolkit.telemetry.bhrPing.enabled",false);
user_pref("toolkit.telemetry.firstShutdownPing.enabled",false);
user_pref("toolkit.telemetry.coverage.opt-out",true);
user_pref("toolkit.coverage.opt-out",true);
user_pref("toolkit.coverage.endpoint.base","");
user_pref("browser.startup.homepage_override.mstone","ignore");
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons",false);
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features",false);
user_pref("browser.urlbar.showSearchTerms.enabled",false);

/* Zen Browser */
user_pref("browser.newtabpage.activity-stream.default.sites", "");
user_pref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
user_pref("browser.newtabpage.activity-stream.feeds.system.topsites", false);
user_pref("browser.newtabpage.activity-stream.feeds.system.topstories", false);
user_pref("browser.newtabpage.activity-stream.section.highlights.includeBookmarks", false);
user_pref("browser.newtabpage.activity-stream.section.highlights.includeDownloads", false);
user_pref("browser.newtabpage.activity-stream.section.highlights.includeVisited", false);
user_pref("browser.newtabpage.activity-stream.showSearch", false);
user_pref("privacy.userContext.enabled", false);
user_pref("privacy.globalprivacycontrol.enabled", false);

/* Search settings */
user_pref("browser.search.separatePrivateDefault", false);
user_pref("browser.urlbar.suggest.recentsearches", false);
user_pref("browser.urlbar.suggest.bookmark", false);
user_pref("browser.urlbar.suggest.clipboard", false);
user_pref("browser.urlbar.suggest.engines", false);
user_pref("browser.urlbar.suggest.history", false);
user_pref("browser.urlbar.suggest.openpage", false);
user_pref("browser.urlbar.shortcuts.bookmarks", false);
user_pref("browser.urlbar.shortcuts.history", false);
user_pref("browser.urlbar.shortcuts.tabs", false);
user_pref("browser.urlbar.showSearchSuggestionsFirst", false);
user_pref("browser.search.separatePrivateDefault", false);

/* Dns */
user_pref("network.trr.mode", 3);

/* Save/Remember passwords & addresses */
user_pref("signon.rememberSignons", false);
user_pref("signon.firefoxRelay.feature", "disabled");
user_pref("signon.generation.enabled", false);
user_pref("signon.management.page.breach-alerts.enabled", false);
user_pref("extensions.formautofill.addresses.enabled", false);
user_pref("extensions.formautofill.creditCards.enabled", false);

/* Theme and UI */
user_pref("zen.tab-unloader.enabled", false);
user_pref("zen.tabs.show-newtab-vertical", false);
user_pref("zen.theme.accent-color", "#ffc0cb");
user_pref("zen.theme.color-prefs.use-workspace-colors", false);
user_pref("zen.view.compact.color-sidebar", false);
user_pref("zen.view.compact.color-toolbar", false);
user_pref("zen.view.show-newtab-button-top", false);
user_pref("zen.view.sidebar-expanded", false);
user_pref("zen.view.use-single-toolbar", false);
user_pref("zen.welcome-screen.seen", true);
user_pref("zen.view.experimental-no-window-controls", true)